import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUiProvider } from "./Components/NextUiProvider";
import SessionAuthProvider from "./Providers/SessionAuthProvider";
import UserContextProvider from "./Providers/UserContextProvider";
import Sidebar from "./Components/Sidebar";
import Applayout from "./Components/Applayout.tsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionAuthProvider>
          <UserContextProvider>
            <NextUiProvider>
              <Applayout>{children}</Applayout>
            </NextUiProvider>
          </UserContextProvider>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
